## 12. Conclusion

This project investigated WhatsHap-based long-read phasing through a controlled synthetic benchmarking framework designed to balance realism, attribution, and experimental flexibility. The main objective was not only to measure phasing performance, but also to understand where performance is lost in practical end-to-end conditions and to identify optimization directions that are genuinely useful.

The project makes three main contributions. First, it establishes a realistic and configurable benchmarking pipeline that supports both oracle and called regimes. This makes it possible to separate phaser-limited behaviour from full end-to-end behaviour and to attribute losses to variant recovery, phasing completeness, or phase correctness. The framework also supports multiple realism stressors, including duplicated regions, coverage dropout, correlated error bursts, variable read-length models, and truth indels with SNP-only safeguards. This makes the platform useful not only for reporting performance, but also for studying how different conditions affect WhatsHap-based phasing mechanisms. 

Second, the experiments show that end-to-end performance is often limited less by the phasing algorithm itself than by the quality and overlap of informative heterozygous variants that survive upstream processing. In the oracle regime, WhatsHap remains highly accurate once correct sites are available, while the called regime often shows larger losses due to missing shared heterozygous sites and reduced connectivity. Among the isolated realism knobs, coverage dropout was the strongest stressor, acting primarily through fragmentation and later also through reduced variant recovery. The duplication × dropout interaction further showed that realistic difficulty is often compounded rather than purely additive, with mixed caller-side and phaser-side weaknesses emerging most clearly under combined stress. 

Third, the optimization study shows that useful but limited practical headroom exists. The strongest positive result came from caller-side base-quality tuning: reducing `call_min_baseq` to a moderate value improved call recall, shared heterozygous overlap, and end-to-end phased recall without materially harming precision. On the phasing side, the main lesson was to avoid overly strict filtering: `min_baseq = 20` was consistently harmful, whereas moderate values such as `10` lay on a stable performance plateau. Retained coverage also showed a practical runtime trade-off, with `max_coverage = 8` or `10` preserving performance while avoiding unnecessary compute. The recommended general setting for this pipeline is therefore `call_min_baseq = 10`, `max_coverage = 8`, and `min_baseq = 10`, with `call_min_mapq = 20` and `min_mapq = 20` retained as practical defaults. A slightly more runtime-biased alternative using `max_coverage = 6` performs almost identically on the main accuracy metrics and may also be acceptable when efficiency is prioritized. 

Taken together, the results support a pipeline-level view of WhatsHap optimization. WhatsHap itself is robust when informative variant evidence is available, but end-to-end performance depends strongly on upstream variant recovery, read connectivity, and compounded realistic stress. Practical gains are therefore most likely to come from preserving useful evidence across the pipeline and from combining moderate caller-side and phasing-side tuning, rather than from aggressive tuning of a single parameter or from focusing only on the phasing solver in isolation. 

Several future directions follow naturally from this work. These include validating the recommended settings on broader and more realistic datasets, studying upstream variant recovery more directly, deepening the algorithm-facing analysis of residual solver difficulty, comparing the project-specific adaptor against the standard WhatsHap front-end, and exploring region-aware optimization strategies under compounded stress. Overall, the project provides both a reproducible evaluation platform and a practical set of experimentally supported recommendations for more effective WhatsHap-based long-read phasing. 